packages:
  - apps/*

catalogMode: prefer

catalog:
  "@types/node": ^24
  bun-types: ^1.4.2
  elysia: ^1.4.30
  turbo: ^2.11.5
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vite-plus: 1.0.0
  vitest: ^5.0.3
  wrangler: ^4.145.0
  zod: ^4.6.5
overrides:
  vite@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
allowBuilds:
  esbuild: true
  sharp: false
  unrs-resolver: false
  workerd: true
